### ISSUE TITLE
容器内执行 exit 命令，容器挂掉

### ISSUE THREAD

**Issue by xiamf** [qfdk/EasyDockerWeb#12]
你好，你做的docker web特别好用，有一点出现了一点问题，在容器内执行exit退出命令的时候，EasyDockerweb容器会挂掉。有什么解决方案吗？忘修复，谢谢。

**Comment by qfdk** [comment]
@xiamf 

Hi 您好，

容器内部执行exit 命令？ 你是值得是运行EasyDockerWeb的容器 还是你自己的容器呢？

方便给出细节来研究下么

真诚的

**Comment by xiamf** [comment]
您好，
![image](https://user-images.githubusercontent.com/20984431/81661977-814fe900-946f-11ea-9287-600dbd22dec0.png)
如图，当我在自己的容器里执行 exit 命令后，EasyDockerWeb容器会挂掉。

**Comment by xiamf** [comment]
您好，

如图，当我在自己的容器里执行 exit 命令后，EasyDockerWeb容器会挂掉。恳请修复，谢谢。













在 2020-04-29 02:49:07，"qfdk" <notifications@github.com> 写道：

@xiamf

Hi 您好，

容器内部执行exit 命令？ 你是值得是运行EasyDockerWeb的容器 还是你自己的容器呢？

方便给出细节来研究下么

真诚的

**Comment by qfdk** [comment]
@xiamf 这个不是APP的问题。 我想想办法处理吧，因为docker 容器 当你运行的exit 命令，容器会停止，相当于你用docker attach 到你的容器，然后你在容器内部执行命， 连接关闭丢失了。命令内容是为了准备给ls 这样的命令用的。 
回头我思考一下吧

**Comment by xiamf** [comment]
好的，多谢。 
还有一点建议，如果能有容器与本地之间的文件上传和下载功能就完美了。

**Comment by qfdk** [comment]
@xiamf 这个功能你把容器开个ssh 就是了 那个可以复制的。或者你挂载硬盘过去都可以的，以前的版本有做

**Comment by brezhitskiy42** [comment]
Hello. Is there any solution for this problem? I mean that the terminal hangs up when you enter `exit`.

**Comment by qfdk** [comment]
Hello @brezhitskiy42, 

The container detach the streaming when you hit exit command.
There are 2 ways to resolve this 'problem":
- add some control in the condition (reject exit command)
- F5 (refresh) page
