### ISSUE TITLE
显示实时内存占用

### ISSUE THREAD

**Issue by amwson** [qfdk/EasyDockerWeb#5]
希望添加一个功能，当前实时的内存占用率，具体数据为： 在shell里面输入 docker stats containerId 后，界面里面显示的MEM USAGE。

现在的版本有CPU实时占用率，如果加上实时MEM就很完美了。

**Comment by qfdk** [comment]
@amwson hi 有空会看看如何计算，现在基本是简单为主。

**Comment by amwson** [comment]
多谢多谢！

> @amwson hi 有空会看看如何计算，现在基本是简单为主。

**Comment by qfdk** [comment]
@amwson 您好

显示RAM的占用率已经添加，该问题关闭

**Comment by amwson** [comment]
多谢多谢

在 2019-07-08 21:37:11，"qfdk" <notifications@github.com> 写道：


@amwson 您好

显示RAM的占用率已经添加，该问题关闭
