### ISSUE TITLE
功能建议。

### ISSUE THREAD

**Issue by zsq19958629** [qfdk/EasyDockerWeb#6]
我很喜欢你开发的这个UI，不过在创建容器的那个界面，不是很合理。
koolshare制作的lede能够运行docker，他在创建容器的时候，给用户的自由度比较大。

只有三个选项：1、容器名称。2、容器是否需要开机运行。3、命令行参数。
最终合成的命令行内容是如下格式：
【docker run -d】{ --name Aria2Service} <-p 6800:6800 -p 3002:80 -p 3003:8080 -v /mnt/ssd/download:/aria2/downloads -v /mnt/ssd/Aria2NG:/aria2/conf -e SECRET=99010> {--restart=always} 【jinlife/aria2-ariang】
【】括号内的是固定生成的，{}括号内是可选填写的（就是选项1和2）<>括号内的是命令行参数（就是选项3）

可以参考这种模式制作新建容器的界面选项。感觉给人更多自由度。
当然，这只是我的一点拙见。

**Comment by qfdk** [comment]
@zsq19958629 感谢您的建议，有时间可以考虑加上。
您方便有空的时候可以提交下pr

**Comment by qfdk** [comment]
@zsq19958629 hi 您好 1,2 点已经完成了,可以测试一下啦. https://github.com/qfdk/EasyDockerWeb/commit/d36f267f0b9bb9c329f7e7cb80eac37a74beb350
