### ISSUE TITLE
[Request] Add ARM64 support

### ISSUE THREAD

**Issue by spider1163** [qfdk/EasyDockerWeb#66]
Hello,

Please add support for ARM64 architecture (Raspberry Pi for example)

Thank you

**Comment by qfdk** [comment]
@spider1163 
Hello,
I will work on it when i have some free time.

**Comment by qfdk** [comment]
@spider1163 ,
It works with arm64, tested with server oracle 4C/24Gb

**Comment by spider1163** [comment]
> @spider1163 , It works with arm64, tested with server oracle 4C/24Gb

Hello, 
is there a tag for ARM64 ?
```

$ docker run -it -d -p 3000:3000 -e EDW_USERNAME='admin' -e EDW_PASSWORD='admin' -v /var/run/docker.sock:/var/run/docker.sock qfdk/easydockerweb
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
9a059e2d5e4a1b610eb26209ffd7a8a8f688b211a6dea7d5c815fb3c9faafea4
```

**Comment by qfdk** [comment]
@spider1163 HEllo, only miss an image for  arm64.  The code have tested with arm64 env

**Comment by qfdk** [comment]
@spider1163 I have push a new image, https://hub.docker.com/layers/qfdk/easydockerweb/latest/images/sha256-185f6b11bbf2cd8ed42ea25f117a23434772552c7c49b1d4f1c9fb40742631b6?context=repo

now it supported with arm64

**Comment by qfdk** [comment]
@if1y I'm sorry, i will try to fix that.
