### ISSUE TITLE
[Bug] Inproper arch for default docker image

### ISSUE THREAD

**Issue by jingfelix** [qfdk/EasyDockerWeb#70]
After #66 , `docker pull qfdk/easydockerweb`will pull the image for arm64 despite current CPU arch.

I guess this can be solved by adding manifest for different os/arch.

**Comment by jingfelix** [comment]
I will try to fix this in my [fork](https://github.com/jingfelix/EasyDockerWeb), as well as using GitHub Action to build and push automatically.

**Comment by qfdk** [comment]
@jingfelix 
I have fixed it with arm/arm64/amd64
Thanks for help
