### ISSUE TITLE
建议后台增加密码登录

### ISSUE THREAD

**Issue by xiaoxinpro** [qfdk/EasyDockerWeb#8]
首先非常感谢这个项目，真的非常好用。

我的使用场景在外网的vps上面，所以没密码登录是非常不安全的。

可以使用简单的HTTPAUTH，总比没有强很多。

希望可以采纳，谢谢！

**Comment by qfdk** [comment]
#3 加密码方式 参考这里 @xiaoxinpro

**Comment by qfdk** [comment]
@xiaoxinpro 时隔一年 添加了一个简单的认证页面

**Comment by if1y** [comment]
> @xiaoxinpro 时隔一年 添加了一个简单的认证页面

如何定义默认密码呢

**Comment by qfdk** [comment]
@if1y 默认密码 admin 可以再 security 文件 里面修改一下。 或者你可以拿出来用配置文件

**Comment by if1y** [comment]
> @if1y 默认密码 admin 可以再 security 文件 里面修改一下。 或者你可以拿出来用配置文件

好的。
如果能用 `-p PASSWORD=` 指定的话就更方便了。

**Comment by qfdk** [comment]
@if1y 嗯好建议，其实可以改一下那个文件 改成 password = precess.env.PASSWORD||'admin' 这样 如果有设置这个变量 会用这个变量，默认密码 admin， 这样方便 docker

**Comment by qfdk** [comment]
@if1y 已经更新了。

**Comment by if1y** [comment]
> @if1y 已经更新了。

谢谢

**Comment by qfdk** [comment]
@if1y  docker 方式的话 可以 这样 `docker run -it -d -p 3000:3000 -e EDW_USERNAME='admin' -e EDW_PASSWORD='admin' -v /var/run/docker.sock:/var/run/docker.sock qfdk/easydockerweb`
