### ISSUE TITLE
Add a case for pulling an incorrect image

### ISSUE THREAD

**Issue by EdgarLGB** [qfdk/EasyDockerWeb#9]
Hi,

I like your Docker UI tool and I gave it a try. I found some space of improvement. I tried to pull an image which does not exist actually and now the page is stuck on **waiting**. After a while, the server got killed. I think that we should manage to handle pulling the wrong image.

**Comment by qfdk** [comment]
Hi,
The program use auto-completion to get the right image. To handle this case, we will find a solution, but it's not a issue for me.

**Comment by qfdk** [comment]
#

**Comment by qfdk** [comment]
@EdgarLGB The problem was fixed in the latest commit.https://github.com/qfdk/EasyDockerWeb/commit/92b6d33dd7b567ce632f48279bdbe2d72e485183
